name: savinfo-ci

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            SMS_API_USERNAME: ${{ secrets.SMS_API_USERNAME }}
            SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
            SENDER_SHORTCODE: ${{ secrets.SENDER_SHORTCODE }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            
            - name: Run tests with coverage
              run: |
                coverage run -m pytest --ds=savinfo.settings
                coverage report -m