name: savinfo-ci

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            SMS_API_USERNAME: ${{ secrets.SMS_API_USERNAME }}
            SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
            SENDER_SHORTCODE: ${{ secrets.SENDER_SHORTCODE }}

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: my_test_db
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                ports:
                    - 5432:5432
                options:
                    --health-cmd "pg_isready -U user"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            
            - name: Apply database migrations
              run: python manage.py migrate
            
            - name: Run tests with coverage
              run: |
                coverage run -m pytest --ds=savinfo.settings
                coverage report -m